#! /bin/sh

### auto start
# Simple x hot key deamon
pgrep -x sxhkd > /dev/null || sxhkd &
# effects
picom -f &
# wallpaper
feh --bg-fill --randomize $HOME/Pictures/* &
# fix the cursor
xsetroot -cursor_name left_ptr


### BSPWM Config
bspc monitor -d I II III IV V VI

bspc config normal_border_color	   "#ff000"
bspc config active_border_color    "#00ff00" 
bspc config focused_border_color   "#A3BE8C"
bspc config presel_feedback_color  "#4C566A"
#bspc config urgent_border_color    "#BF616A"
bspc config urgent_border_color    "#0000ff"

bspc config border_width        2 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a code-oss desktop='^3'
bspc rule -a Tk state=floating 
